services:
    database:
        image: mysql:8.0.36
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: monetary
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - ./.data/mysql:/var/lib/mysql